create table users
(
    ID            int auto_increment
        primary key,
    USER_NAME     varchar(50)                           not null,
    EMAIL         varchar(100)                          not null,
    PASSWORD      varchar(255)                          not null,
    AVATAR        varchar(255)                          null,
    LAST_LOGIN_DT datetime                              null,
    USED_YN       varchar(1)  default 'Y'               null,
    REG_DT        datetime    default CURRENT_TIMESTAMP null,
    REG_ID        int                                   null,
    MOD_DT        datetime                              null,
    MOD_ID        int                                   null,
    SSO_ID        varchar(50)                           null,
    LOGIN_TYPE    varchar(20) default 'SELF'            null,
    EMAIL_SEND_YN varchar(1)                            null,
    EMAIL_SEND_DT datetime                              null,
    VERIFY_YN     varchar(1)                            null,
    VERIFY_DT     datetime                              null,
    VERIFY_CODE   varchar(6)                            null,
    constraint EMAIL
        unique (EMAIL)
);

INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('tuan ngoc', 'admin01@gmail.com', '$2a$10$bIb7y1.djxpBqPnCIQ8inu.hGp1absPCnkWlA2bJqW58GboRzZT1q', '20240514/1715668252488_25bfd7e104c8499a9ceb3cf1d1307dec.png', '2025-11-07 05:23:00', 'Y', '2023-12-07 13:16:23', null, '2024-05-22 01:24:38', 3, null, 'SELF', null, null, 'Y', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('ngoc (응옥)', 'admin02@gmail.com', '$2a$10$bIb7y1.djxpBqPnCIQ8inu.hGp1absPCnkWlA2bJqW58GboRzZT1q', '20240514/1715773890986_5ad9509d81b24747acccdae903970659.png', '2024-06-10 06:25:59', 'Y', '2023-12-07 14:36:16', null, '2024-05-27 02:38:00', 3, null, 'SELF', 'N', '2024-06-10 06:17:07', 'Y', '2024-06-10 04:19:19', '953460');
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('Hoàng Tuấn Ngọc', 'htngoc0916@gmail.com', '$2a$10$I91Q7ztJ2qpCc.PXY4.iTu7qUIuO2tXIDKjC9DAvXjj9cGEk5/6Fe', 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=1977186949382558&height=50&width=50&ext=1719737845&hash=AbaIABvfSu6hdYxqjuAkYlLd', '2024-06-03 01:17:08', 'Y', '2024-05-14 13:13:12', null, '2024-05-24 07:53:31', 3, null, 'SELF', 'Y', '2024-06-05 07:31:18', 'N', null, '633056');
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('tester', 'tester01@gmail.com', '$2a$10$pC19DDvzc88MTLgAyKORme/aetmCJUoiCwZWOTWRoARpJfkux/b6K', null, '2024-06-10 05:15:31', 'Y', '2024-05-27 02:38:33', null, null, null, null, 'SELF', 'Y', null, 'Y', '2024-06-10 14:15:07', null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('hoangtuan', 'tester02@gmail.com', '$2a$10$.zcQ3kEXd.UPl1DxGuUsE.HM4JNr0VvNLMGMMd3967GSLYQncpoli', null, null, 'Y', null, null, null, null, null, 'SELF', null, null, null, null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('testet', 'tester04@gmail.com', '$2a$10$9jqDpTgwFTkxdJNAQlz34OT4LpBO/8v/viCGnpUx/maslgZTonotK', null, '2024-06-10 05:14:51', 'Y', null, null, null, null, null, 'SELF', null, null, null, null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('tesst123', 'teset@gmail.com', '2345', '', '2024-05-29 13:36:34', 'Y', '2024-05-29 13:36:34', null, null, null, null, 'SELF', null, null, null, null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('test05', 'test05@gmail.com', '$2a$10$ezqtTp3aZtJEHGap6SRZBeYp/z57UL1VULrgLxO9rXFTR2hQJRiHO', null, null, 'Y', null, null, null, null, null, 'SELF', '', null, null, null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('teee', 'teseaaat@gmail.com', '$2a$10$bUSodDOZWs8vPotVVztjfedx..mHDU4KfLs/bFjk1HP.4hQvfqoN2', null, null, 'Y', null, null, null, null, null, null, 'Y', '2024-06-07 06:41:22', 'N', null, '830703');
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('test email', 'ngocbn73@gmail.com', '$2a$10$lZMDUgvEu8siZOAa1T958Our.XncPtYKjYLc2.HroRyB61HYyDVri', null, null, 'Y', null, null, null, null, null, null, 'Y', '2024-06-07 06:52:23', 'Y', '2024-06-07 06:52:53', '183560');
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser01@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser001@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser002@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser003@gmail.com', '123456', null, null, null, null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser004@gmail.com', '123456', null, null, null, null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser005@gmail.com', '123456', null, null, null, null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser006@gmail.com', '123456', null, null, null, null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser007@gmail.com', '123456', null, null, null, null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser008@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser009@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser010@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser011@gmail.com', '123456', null, null, 'Y', null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser012@gmail.com', '123456', null, null, null, null, null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser013@gmail.com', '123456', null, null, 'Y', '2025-11-26 04:58:36', null, '2025-11-26 04:58:36', null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser014@gmail.com', '123456', null, null, 'Y', '2025-11-26 05:07:00', null, null, null, null, null, null, null, 'N', null, null);
INSERT INTO `blog-htngoc`.users (USER_NAME, EMAIL, PASSWORD, AVATAR, LAST_LOGIN_DT, USED_YN, REG_DT, REG_ID, MOD_DT, MOD_ID, SSO_ID, LOGIN_TYPE, EMAIL_SEND_YN, EMAIL_SEND_DT, VERIFY_YN, VERIFY_DT, VERIFY_CODE) VALUES ('htn', 'testuser015@gmail.com', '123456', null, null, 'Y', '2025-11-27 07:54:27', null, null, null, null, null, null, null, 'N', null, '397088');
